# Generated by Django 3.2.2 on 2021-07-14 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chemcomp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synthesize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_years', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('chance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chemcomps', models.ManyToManyField(to='core.Chemcomp')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
