# Generated by Django 3.2.2 on 2021-07-17 22:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_synthesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesize',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.synthesize_image_file_path),
        ),
    ]
